### PR TITLE
Move VDFParser to submodule

### PR DESCRIPTION
**Pull request by FlaminSarge**
Reference @heyvito's repo directly instead of copying the files into this repo.

This also picks up the changes from that repo for the new shortcuts.vdf fields, so that (eventually) UWPHook won't remove LaunchOptions/other fields from existing shortcuts.

Build succeeds in VS2019 with no changes to csproj. Verified newly built DLLs against UWPHook.exe already; LastPlayTime and LaunchOptions no longer get removed every time UWPHook updates shortcuts.

### CODE REVIEW

**Comment by heyvito** [comment]
Seems okay, but I personally try to avoid git modules at all costs.
I'm far from Microsoft tooling for a good while now; is there any way to make VDFParser a dependency of some kind?

Still about vendoring: @BrianLima your project lacks a proper license. Could you please comply with VDFParser's license? Thanks!

**Comment by FlaminSarge** [comment]
If VDFParser were available on NuGet then I don't think we'd need the submodule, but until then, submodule's definitely better than copying the entire VDFParser codebase into this.

**Comment by BrianLima** [comment]
@FlaminSarge Thanks for the heads-up and for going out of your way to fix some things! I created a release for this lib and started work on a small patch for UWPHook.
@heyvito Added a license at #2.

**Comment by heyvito** [comment]
Thanks @BrianLima :)

**Pull request merged**
